platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"
pod 'FlatUIKit', '~> 1.2'
pod 'UMengAnalytics', '~> 2.2.1'
pod 'SWTableViewCell', '~> 0.2.1'
pod 'iOS7Colors', '~> 2.1.0'
pod 'KXKiOS7ColorsAndGradients', '~> 1.0.0'
pod 'SDWebImage', '~> 3.5.1'
pod 'FMDB', '~> 2.1'
pod 'MTLog', '~> 0.6.1'
